export { default as Logotipo } from "./Logotipo";
export { default as Facebook } from "./Facebook";
export { default as Isotipo } from "./Isotipo";
export { default as Geko} from "./Geko";
export { default as LikeIcon} from "./LikeIcon";
export { default as UnlikeIcon} from "./UnlikeIcon";
export { default as CommentIcon} from "./CommentIcon";
export { default as ShareIcon} from "./ShareIcon";
export { default as MoreIcon} from "./MoreIcon";
export { default as HomeIcon} from "./HomeIcon";
export { default as SearchIcon} from "./SearchIcon";
export { default as BurguerMenuIcon} from "./BurguerMenuIcon";
